id: ID95003DA
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-12T17:24:01+00:00'
last_modified: '2022-06-15T16:27:35.497374+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1PD90121
  title: མའོ་རྫོང་གི་ས་ཆའི་མིང་བཏུས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    5EAF:
      image_group_id: I1PD90137
      title: Volume 1 of mao wen qiang zu zi zhi xian di ming lu
      total_pages: 220
      order: 1
      base_file: 5EAF.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
